using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace Tollbound.Model
{
    /// <summary>
    /// Progression rungs, in order. The numeric value is the ordering used for ceiling
    /// checks: a portal carries its own tier and everything below it.
    /// </summary>
    internal enum BiomeTier
    {
        None = 0,
        BlackForest = 1,
        Swamp = 2,
        Mountain = 3,
        Plains = 4,
        Mistlands = 5,
        Ashlands = 6,
    }

    /// <summary>
    /// Everything that varies per rung, in one place. Prefab and item names below were
    /// taken from the item report generated by a real game start, not from recall.
    /// </summary>
    internal sealed class TierInfo
    {
        internal BiomeTier Tier;

        /// <summary>Prefab name of the portal piece this mod creates for the tier.</summary>
        internal string PortalPrefab;

        /// <summary>Localization token for the piece name.</summary>
        internal string NameToken;

        internal string DisplayName;
        internal string Description;

        /// <summary>The boss whose spirit collects the toll, for message copy.</summary>
        internal string SpiritName;

        /// <summary>
        /// Global key set when the boss dies. Checked with the string overload of
        /// ZoneSystem.GetGlobalKey, because Queen and Fader have no GlobalKeys enum member.
        /// </summary>
        internal string BossKey;

        /// <summary>Base hue. Scaled up for the connected glow, down for the idle tint.</summary>
        internal Color Hue;

        internal string DefaultTollItem;
        internal int DefaultTollAmount;

        /// <summary>Per-unit chance to lose this tier's metal while its boss lives.</summary>
        internal float DefaultLossRate;

        internal string CraftingStation;

        /// <summary>Build cost as (prefab, amount) pairs.</summary>
        internal (string Item, int Amount)[] Recipe;

        /// <summary>Cargo this rung admits that lower rungs do not.</summary>
        internal string[] Cargo;

        /// <summary>
        /// The subset of <see cref="Cargo"/> that can be destroyed in transit. Ores and
        /// bars only: quest and mechanism items are gated by tier but never taken, because
        /// they are irreplaceable.
        /// </summary>
        internal string[] LossEligible;
    }

    internal static class Tiers
    {
        internal static readonly TierInfo[] All =
        {
            new TierInfo
            {
                Tier = BiomeTier.BlackForest,
                PortalPrefab = "portal_tollbound_blackforest",
                NameToken = "$piece_tollbound_blackforest",
                DisplayName = "Portal - Black Forest",
                Description = "Carries copper and tin. The Elder counts what leaves his woods.",
                SpiritName = "the Elder",
                BossKey = "defeated_gdking",
                Hue = new Color(0.25f, 1.00f, 0.30f),
                DefaultTollItem = "GreydwarfEye",
                DefaultTollAmount = 5,
                DefaultLossRate = 0.05f,
                CraftingStation = Jotunn.Configs.CraftingStations.Workbench,
                Recipe = new[] { ("FineWood", 20), ("GreydwarfEye", 10), ("SurtlingCore", 2), ("Copper", 5) },
                Cargo = new[] { "CopperOre", "TinOre", "Copper", "Tin", "Bronze", "BronzeScrap", "CopperScrap" },
                LossEligible = new[] { "CopperOre", "TinOre", "Copper", "Tin", "Bronze", "BronzeScrap", "CopperScrap" },
            },
            new TierInfo
            {
                Tier = BiomeTier.Swamp,
                PortalPrefab = "portal_tollbound_swamp",
                NameToken = "$piece_tollbound_swamp",
                DisplayName = "Portal - Swamp",
                Description = "Carries iron. Bonemass keeps what the mire is owed.",
                SpiritName = "Bonemass",
                BossKey = "defeated_bonemass",
                Hue = new Color(0.75f, 0.95f, 0.20f),
                DefaultTollItem = "Entrails",
                DefaultTollAmount = 6,
                DefaultLossRate = 0.07f,
                CraftingStation = Jotunn.Configs.CraftingStations.Workbench,
                // ElderBark, not AncientBark: the display name and the prefab name differ.
                Recipe = new[] { ("FineWood", 20), ("ElderBark", 10), ("SurtlingCore", 2), ("Iron", 5) },
                Cargo = new[] { "IronOre", "IronScrap", "Iron" },
                LossEligible = new[] { "IronOre", "IronScrap", "Iron" },
            },
            new TierInfo
            {
                Tier = BiomeTier.Mountain,
                PortalPrefab = "portal_tollbound_mountain",
                NameToken = "$piece_tollbound_mountain",
                DisplayName = "Portal - Mountain",
                Description = "Carries silver and dragon eggs. Moder counts what you carry.",
                SpiritName = "Moder",
                BossKey = "defeated_dragon",
                Hue = new Color(0.45f, 0.85f, 1.00f),
                DefaultTollItem = "FreezeGland",
                DefaultTollAmount = 4,
                DefaultLossRate = 0.09f,
                CraftingStation = Jotunn.Configs.CraftingStations.Forge,
                Recipe = new[] { ("FineWood", 20), ("Obsidian", 10), ("SurtlingCore", 2), ("Silver", 5) },
                Cargo = new[] { "SilverOre", "Silver", "DragonEgg" },
                // DragonEgg is protected: gated by tier, never destroyed.
                LossEligible = new[] { "SilverOre", "Silver" },
            },
            new TierInfo
            {
                Tier = BiomeTier.Plains,
                PortalPrefab = "portal_tollbound_plains",
                NameToken = "$piece_tollbound_plains",
                DisplayName = "Portal - Plains",
                Description = "Carries black metal. Yagluth's hand still closes.",
                SpiritName = "Yagluth",
                BossKey = "defeated_goblinking",
                Hue = new Color(1.00f, 0.72f, 0.20f),
                DefaultTollItem = "Needle",
                DefaultTollAmount = 5,
                DefaultLossRate = 0.11f,
                CraftingStation = Jotunn.Configs.CraftingStations.Forge,
                Recipe = new[] { ("FineWood", 20), ("Needle", 10), ("SurtlingCore", 2), ("BlackMetal", 5) },
                Cargo = new[] { "BlackMetalScrap", "BlackMetal" },
                LossEligible = new[] { "BlackMetalScrap", "BlackMetal" },
            },
            new TierInfo
            {
                Tier = BiomeTier.Mistlands,
                PortalPrefab = "portal_tollbound_mistlands",
                NameToken = "$piece_tollbound_mistlands",
                DisplayName = "Portal - Mistlands",
                Description = "Carries extractors and Hildir's chests. Nothing crosses without her leave.",
                SpiritName = "the Queen",
                BossKey = "defeated_queen",
                Hue = new Color(0.62f, 0.35f, 1.00f),
                DefaultTollItem = "Bilebag",
                DefaultTollAmount = 4,
                // Nothing this rung admits is loss-eligible, so the rate never fires.
                // Kept configurable in case a future item is added to the tier.
                DefaultLossRate = 0f,
                CraftingStation = Jotunn.Configs.CraftingStations.ArtisanTable,
                Recipe = new[] { ("YggdrasilWood", 20), ("BlackMarble", 10), ("SurtlingCore", 4), ("Eitr", 2) },
                Cargo = new[] { "DvergrNeedle", "chest_hildir1", "chest_hildir2", "chest_hildir3" },
                LossEligible = new string[0],
            },
            new TierInfo
            {
                Tier = BiomeTier.Ashlands,
                PortalPrefab = "portal_tollbound_ashlands",
                NameToken = "$piece_tollbound_ashlands",
                DisplayName = "Portal - Ashlands",
                Description = "Carries flametal. The last flame takes its portion.",
                SpiritName = "Fader",
                BossKey = "defeated_fader",
                Hue = new Color(1.00f, 0.35f, 0.10f),
                DefaultTollItem = "CharredBone",
                DefaultTollAmount = 5,
                DefaultLossRate = 0.15f,
                CraftingStation = Jotunn.Configs.CraftingStations.BlackForge,
                // FlametalNew is the current Ashlands metal; bare "Flametal" is the
                // legacy pre-Ashlands item, display name "Ancient Metal".
                Recipe = new[] { ("Blackwood", 20), ("Grausten", 10), ("SurtlingCore", 4), ("FlametalNew", 5) },
                Cargo = new[]
                {
                    "FlametalOre", "FlametalOreNew", "Flametal", "FlametalNew",
                    "CharredCogwheel", "MechanicalSpring", "Ironpit",
                },
                // Legacy flametal included so old saves behave the same.
                LossEligible = new[] { "FlametalOre", "FlametalOreNew", "Flametal", "FlametalNew" },
            },
        };

        private static readonly Dictionary<BiomeTier, TierInfo> ByTier =
            All.ToDictionary(t => t.Tier);

        private static readonly Dictionary<string, TierInfo> ByPortalPrefab =
            All.ToDictionary(t => t.PortalPrefab, System.StringComparer.OrdinalIgnoreCase);

        internal static TierInfo Get(BiomeTier tier) =>
            ByTier.TryGetValue(tier, out var info) ? info : null;

        /// <summary>
        /// The tier a portal prefab grants, or None for wood, stone and anything else this
        /// mod did not create. Callers use None to mean "leave vanilla alone".
        /// </summary>
        internal static BiomeTier TierOfPortal(string prefabName)
        {
            if (string.IsNullOrEmpty(prefabName))
            {
                return BiomeTier.None;
            }

            // Instantiated objects carry the "(Clone)" suffix.
            var clean = prefabName.EndsWith("(Clone)")
                ? prefabName.Substring(0, prefabName.Length - 7)
                : prefabName;

            return ByPortalPrefab.TryGetValue(clean, out var info) ? info.Tier : BiomeTier.None;
        }

        internal static bool IsTollboundPortal(string prefabName) =>
            TierOfPortal(prefabName) != BiomeTier.None;
    }
}
